### ISSUE TITLE
nested webpages

### ISSUE THREAD

**Issue by lhaycock** [joewheaton-org/etal#1]
@philipbaileynar On [this](http://etal.joewheaton.org/resources/how-to-guides/writing-resources/writing-scientific-papers) page, can you help me figure out how there is essentially another page within the page of conservationbytes.com.  How do I mimic that in typora?

**Comment by philipbaileynar** [comment]
I believe that he is using a HTML IFRAME tag. See this resource:

https://www.w3schools.com/tags/tag_iframe.asp

Iframes allow you to embed external content within a web page. So you would write something like the following to embed the Google home page within your markdown document: 

```
<iframe src="https://www.google.com"></iframe>
```
